### PR TITLE
Release 0.2.6

### PR DESCRIPTION
**Pull request by lucab**
Changes:
 * tests/e2e-update: Bump to f34 grub
 * workflows: bump toolchains; restrict repository access; fix build/lint warnings
 * OWNERS: remove
 * git: rename master branch to main
 * ci: Update to latest buildroot model
 * cargo: update all dependencies
 * lockfile: general refresh, update all openssl crates

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Thanks!

**Comment by lucab** [comment]
@cgwalters it looks like you are the only owner of this crate, can you please add `github:coreos:fedora-coreos-crates-owners` to it?

**Comment by cgwalters** [comment]
Hmm, do we still need to publish to crates.io?

**Comment by cgwalters** [comment]
```
$ cargo owner --add github:coreos:fedora-coreos-crates-owners bootupd
    Updating crates.io index
       Owner team github:coreos:fedora-coreos-crates-owners has been added as an owner of crate bootupd
$
```

**Comment by lucab** [comment]
Not strictly, but the specfiles are still pointing to it. We can switch out of that at any time, but we need to publish the crate package on GH then.

**Comment by lucab** [comment]
Published: https://crates.io/crates/bootupd/0.2.6
Tagged: https://github.com/coreos/bootupd/releases/tag/v0.2.6

**Pull request merged**
