### PR TITLE
ci: update `uraimo/run-on-arch-action` to v2 latest version

### PR DESCRIPTION
**Pull request by HuijingHei**
See https://github.com/uraimo/run-on-arch-action/issues/155

### CODE REVIEW

**Comment by travier** [comment]
We should add the dependabot config for github actions:

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

**Comment by HuijingHei** [comment]
> We should add the dependabot config for github actions:
> 
> ```
> version: 2
> updates:
>   - package-ecosystem: "github-actions"
>     directory: "/"
>     schedule:
>       interval: "weekly"
> ```

Should add this in https://github.com/coreos/repo-templates/blob/main/.github/dependabot.yml, is this right?

**Comment by travier** [comment]
yes

**Comment by HuijingHei** [comment]
PR is https://github.com/coreos/repo-templates/pull/250

**Pull request merged**
