### PR TITLE
filetree: skip the error if removing unexisting files

### PR DESCRIPTION
**Pull request by HuijingHei**
Fixes https://github.com/coreos/bootupd/issues/762

### CODE REVIEW

**Comment by HuijingHei** [comment]
The `bootupctl validate` failed is because there are some files ( from `shim-ia32` and `grub2-efi-ia32` packages) removed  in `/boot/efi/EFI` compared to `/usr/lib/bootupd/updates/EFI/`, refer to https://github.com/coreos/bootupd/blob/main/src/efi.rs#L413-L420. 

Do we still need the `ia32` files on x64 platform? Check on fedora-coreos we do not have the related `shim-ia32` and `grub2-efi-ia32` packages:
```
$ podman run --rm -it quay.io/fedora/fedora-coreos:testing-devel bash
bash-5.2# rpm -qa | grep grub
grub2-common-2.12-10.fc41.noarch
grub2-pc-modules-2.12-10.fc41.noarch
grub2-tools-minimal-2.12-10.fc41.x86_64
grub2-tools-2.12-10.fc41.x86_64
grub2-efi-x64-2.12-10.fc41.x86_64
grub2-pc-2.12-10.fc41.x86_64
bash-5.2# rpm -qa | grep shim
shim-x64-15.8-3.x86_64

bash-5.2# cat /etc/os-release 
PRETTY_NAME="Fedora CoreOS 41.20241106.20.0"

bash-5.2# ls -al /usr/lib/bootupd/updates/EFI/ -R
/usr/lib/bootupd/updates/EFI/:
total 0
drwxr-xr-x. 1 root root  20 Nov  7 08:21 .
drwxr-xr-x. 1 root root  40 Nov  7 08:21 ..
drwxr-xr-x. 1 root root  40 Nov  7 08:21 BOOT
drwxr-xr-x. 1 root root 100 Nov  7 08:21 fedora

/usr/lib/bootupd/updates/EFI/BOOT:
total 1016
drwxr-xr-x. 1 root root     40 Nov  7 08:21 .
drwxr-xr-x. 1 root root     20 Nov  7 08:21 ..
-rwx------. 4 root root 949424 Jan  1  1970 BOOTX64.EFI
-rwx------. 2 root root  87816 Jan  1  1970 fbx64.efi

/usr/lib/bootupd/updates/EFI/fedora:
total 6664
drwxr-xr-x. 1 root root     100 Nov  7 08:21 .
drwxr-xr-x. 1 root root      20 Nov  7 08:21 ..
-rwx------. 2 root root     110 Jan  1  1970 BOOTX64.CSV
-rwx------. 2 root root 4066624 Jan  1  1970 grubx64.efi
-rwx------. 2 root root  848080 Jan  1  1970 mmx64.efi
-rwx------. 4 root root  949424 Jan  1  1970 shim.efi
-rwx------. 4 root root  949424 Jan  1  1970 shimx64.efi
```

**Comment by HuijingHei** [comment]
Check that we have `shim-ia32-15.8-3.x86_64` and `grub2-efi-ia32-2.12-10.fc41.x86_64` on fedora-silverblue image:
```
fedora@hhei-fedora:~/data$ podman run --rm -it quay.io/fedora/fedora-silverblue:41 bash
bash-5.2# rpm -qa | grep shim
shim-x64-15.8-3.x86_64
shim-ia32-15.8-3.x86_64
bash-5.2# rpm -qa | grep grub2-efi
grub2-efi-ia32-2.12-10.fc41.x86_64
grub2-efi-x64-2.12-10.fc41.x86_64

bash-5.2# ls -al /usr/lib/bootupd/updates/EFI/ -R
/usr/lib/bootupd/updates/EFI/BOOT:
total 1820
drwxr-xr-x. 1 root root     84 Nov  7 08:04 .
drwxr-xr-x. 1 root root     20 Nov  7 08:04 ..
-rwx------. 3 root root 747681 Jan  1  1970 BOOTIA32.EFI
-rwx------. 4 root root 949424 Jan  1  1970 BOOTX64.EFI
-rwx------. 2 root root  70360 Jan  1  1970 fbia32.efi
-rwx------. 2 root root  87816 Jan  1  1970 fbx64.efi

/usr/lib/bootupd/updates/EFI/fedora:
total 11012
drwxr-xr-x. 1 root root     192 Nov  7 08:04 .
drwxr-xr-x. 1 root root      20 Nov  7 08:04 ..
-rwx------. 2 root root     112 Jan  1  1970 BOOTIA32.CSV
-rwx------. 2 root root     110 Jan  1  1970 BOOTX64.CSV
-rwx------. 2 root root 3022144 Jan  1  1970 grubia32.efi
-rwx------. 2 root root 4066624 Jan  1  1970 grubx64.efi
-rwx------. 2 root root  673992 Jan  1  1970 mmia32.efi
-rwx------. 2 root root  848080 Jan  1  1970 mmx64.efi
-rwx------. 4 root root  949424 Jan  1  1970 shim.efi
-rwx------. 3 root root  747681 Jan  1  1970 shimia32.efi
-rwx------. 4 root root  949424 Jan  1  1970 shimx64.efi
```

**Comment by travier** [comment]
It looks like the adoption phase does not install files if they are missing on the disk.

Initially I was thinking that we should not install them but then it means that we can not add new files or rename existing ones. So instead, if bootupd does not find a file on the partition during adoption, it should install it.

**Comment by travier** [comment]
So the test for this case should:
- Setup an EFI folder where some files are missing from the expected list in the bootupd manifest.
- Adopt the system without failing
- Verify that validation does fail on the missing files as we do not install them

Or we could decide to always make sure all files are installed at the end of all update operations.

**Comment by travier** [comment]
In short, I think the code change is right, the test is not.

**Comment by HuijingHei** [comment]
> not install files if they are missing on the disk.

The main reason is that because of `relative_diff_to()`, can not install files if they are missing on the disk, so the unit test is to test that, but agree that should add the integration test for your [comment](https://github.com/coreos/bootupd/pull/765#issuecomment-2464430648).

Failed without the code change:
```
# cargo test filetree::tests::test_apply_with_file
running 1 test
test filetree::tests::test_apply_with_file ... FAILED

failures:

---- filetree::tests::test_apply_with_file stdout ----
Error: test removed files with relative_diff

Caused by:
    0: removing "testfile"
    1: No such file or directory (os error 2)
```

Pass with the change:
```
# cargo test filetree::tests::test_apply_with_file
running 1 test
test filetree::tests::test_apply_with_file ... ok
```

**Comment by HuijingHei** [comment]
> * Verify that validation does fail on the missing files as we do not install them

Do you mean that in this case the validate error is accepted?
```
# bootupctl validate

Removed: BOOT/fbia32.efi
Removed: fedora/BOOTIA32.CSV
Removed: fedora/shimia32.efi
Removed: BOOT/BOOTIA32.EFI
Removed: fedora/grubia32.efi
Removed: fedora/mmia32.efi
error: Caught validation errors
```

**Comment by HuijingHei** [comment]
Thanks @travier for the pointer!
Ready to review, and add test according to Timothée's [comment](https://github.com/coreos/bootupd/pull/765#issuecomment-2464430648).

**Comment by HuijingHei** [comment]
Confused about the CI failed, not sure why the `fuse-libs` is included.

```
Will download: 1 package (98.9?kB)

warning: Found 1 packages to download in cache-only mode

Downloading from 'fedora'...done

error: Installing packages: Downloading from 'fedora': Cannot download Packages/f/fuse-libs-2.9.9-22.fc41.x86_64.rpm: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/fedora/linux/releases/41/Everything/x86_64/os/Packages/f/fuse-libs-2.9.9-22.fc41.x86_64.rpm [Could not resolve host: dl.fedoraproject.org]
```

**Comment by travier** [comment]
> > * Verify that validation does fail on the missing files as we do not install them
> 
> Do you mean that in this case the validate error is accepted?
> 
> ```
> # bootupctl validate
> 
> Removed: BOOT/fbia32.efi
> Removed: fedora/BOOTIA32.CSV
> Removed: fedora/shimia32.efi
> Removed: BOOT/BOOTIA32.EFI
> Removed: fedora/grubia32.efi
> Removed: fedora/mmia32.efi
> error: Caught validation errors
> ```

Yes, right now, if you adopt a system with some files missing, it will fail validate and that's "expected" until we fix the update to also install the missing files.

**Comment by HuijingHei** [comment]
> Yes, right now, if you adopt a system with some files missing, it will fail validate and that's "expected" until we fix the update to also install the missing files.

The validate failed after adopt is because we use [relative_diff_to()](https://github.com/coreos/bootupd/blob/main/src/efi.rs#L278), which will ignore any files or directories that are not part of the original tree, this means we will not install the files from updates dir if they are missing in `/boot/efi/EFI`, this is by design, right? Do you mean we should use [diff()](https://github.com/coreos/bootupd/blob/main/src/efi.rs#L345)?

Maybe we can just ignore the validate error after adopt in this case, if run `update` the next time, then it will use [diff()](https://github.com/coreos/bootupd/blob/main/src/efi.rs#L345) and will install the missing files.

**Comment by HuijingHei** [comment]
Thanks @travier for the rebase.

**Comment by travier** [comment]
> The validate failed after adopt is because we use [relative_diff_to()](https://github.com/coreos/bootupd/blob/main/src/efi.rs#L278), which will ignore any files or directories that are not part of the original tree, this means we will not install the files from updates dir if they are missing in `/boot/efi/EFI`, this is by design, right? Do you mean we should use [diff()](https://github.com/coreos/bootupd/blob/main/src/efi.rs#L345)?
> 
> Maybe we can just ignore the validate error after adopt in this case, if run `update` the next time, then it will use [diff()](https://github.com/coreos/bootupd/blob/main/src/efi.rs#L345) and will install the missing files.

Hum, maybe we should indeed turn those errors into a warning then.

Maybe it looks like the adoption phase does not properly record that those files are missing or maybe it's because I'm calling `update` instead of `adopt-and-update` in the bootloader-update systems unit on Atomic Desktops?

I can reproduce the issue on my system when I remove `/boot/bootupd-state.json` and adopt again.

It not does look like an update re-added the files for me so this would need more testing.

**Comment by HuijingHei** [comment]
> It not does look like an update re-added the files for me so this would need more testing.

Will do more testing for this.

**Comment by travier** [comment]
I've tested that fixes the issue for me on Silverblue. Let's make a release to get this down to Fedora 41.

**Pull request merged**
