### PR TITLE
grubconfig: handle efi vendordir better

### PR DESCRIPTION
**Pull request by HuijingHei**
Fix https://github.com/coreos/bootupd/issues/630

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
This looks sane to me, thanks!

(Longer term we need to stop hardcoding shim...that's it's own issue though)

**Comment by cgwalters** [comment]
Just one unused import to fix from CI

**Comment by cgwalters** [comment]
Hmm, this may have actually broken things, bootc's CI runs with the -dev image that tracks git main started falling over, see

https://github.com/containers/bootc/actions/runs/8443222436/job/23126361204?pr=447

```
error: boot data installation failed: installing component EFI: Updating EFI firmware variables: Locating EFI vendordir: Failed to find EFI vendor dir
```

**Comment by HuijingHei** [comment]
Sorry, `aarch64` does not have `shimx64.efi`, seems we should use `shim.efi` instead.

**Pull request merged**
