### PR TITLE
Release 0.1.3

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
I actually already pushed this to crates, not realizing that branch protection denied direct pushes to master (IMO a good thing).

**Comment by cgwalters** [comment]
Force merging since this is already released.

**Comment by lucab** [comment]
This should really be a 0.2.0 as we dropped the `lib` part which was previously public.

**Comment by lucab** [comment]
Also, the lockfile for this release somehow got out of sync and is stuck at `0.1.1`: https://github.com/coreos/bootupd/blob/v0.1.3/Cargo.lock#L83

**Comment by cgwalters** [comment]
OK https://github.com/coreos/bootupd/pull/79

**Pull request merged**
